name: FTP Connection Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Create test file
        run: mkdir output && echo '{"test":true}' > output/ftp-test.json

      - name: Test FTP connection
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:     ${{ secrets.CYON_FTP_HOST }}
          username:   ${{ secrets.CYON_FTP_USER }}
          password:   ${{ secrets.CYON_FTP_PASSWORD }}
          protocol:   ftps
          local-dir:  ./output/
          server-dir: data/
